delete from vendas_supermercados;
delete from tb_fato;
delete from stg_valores;
delete from stg_supermercados;
delete from stg_produtos;
delete from stg_data;
delete from dim_supermercados;
delete from dim_produtos;
delete from dim_data;