-- Table: public."Produtos"

-- DROP TABLE public."Produtos";

CREATE TABLE public."Produtos"
(
    id_produto integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 0 MINVALUE 0 MAXVALUE 2147483647 CACHE 1 ),
    custounitario_produto double precision,
    precounitario_produto double precision,
    nome_produto character varying COLLATE pg_catalog."default"
    CONSTRAINT "Produtos_pkey" PRIMARY KEY (id_produto)
)

TABLESPACE pg_default;

ALTER TABLE public."Produtos"
    OWNER to postgres;